//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress_contragent
    {
        public int id_adr_contr { get; set; }
        public int id_contragent { get; set; }
        public int id_conec_adress { get; set; }
    
        public virtual Con_adress_Point Con_adress_Point { get; set; }
    }
}
