//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banki
    {
        public int id_bank { get; set; }
        public int name_banka { get; set; }
        public int id_strana { get; set; }
        public int kod_banka { get; set; }
    
        public virtual Strana Strana { get; set; }
    }
}
