//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Con_Adress_Dom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Con_Adress_Dom()
        {
            this.Con_adress_Point = new HashSet<Con_adress_Point>();
        }
    
        public int id_con_adr_dom { get; set; }
        public int id_ulica { get; set; }
        public string nomer_name_doma { get; set; }
    
        public virtual Ulica Ulica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Con_adress_Point> Con_adress_Point { get; set; }
    }
}
