//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contragenti_contact
    {
        public int id_contr_cont { get; set; }
        public int id_contrag { get; set; }
        public int id_contact { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Contragenti Contragenti { get; set; }
    }
}
