//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contragenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contragenti()
        {
            this.Buchalteryas = new HashSet<Buchalterya>();
            this.Contragenti_contact = new HashSet<Contragenti_contact>();
        }
    
        public int id_contr { get; set; }
        public string name_contr { get; set; }
        public int id_adr_contr { get; set; }
        public int id_chet_inbank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchalterya> Buchalteryas { get; set; }
        public virtual Chet_inBank Chet_inBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contragenti_contact> Contragenti_contact { get; set; }
    }
}
