//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Dvijenie_Documenta = new HashSet<Dvijenie_Documenta>();
        }
    
        public int id_doc { get; set; }
        public int id_tip_doc { get; set; }
        public string name_doc { get; set; }
        public int id_otd { get; set; }
        public int id_vid_doc { get; set; }
        public int id_sotrud_from { get; set; }
        public int id_sotrud_to { get; set; }
    
        public virtual Otdely Otdely { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Sotrudniki Sotrudniki1 { get; set; }
        public virtual Tip_Documenta Tip_Documenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dvijenie_Documenta> Dvijenie_Documenta { get; set; }
    }
}
