//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dvijenie_Documenta
    {
        public int id_dv_doc { get; set; }
        public int id_doc { get; set; }
        public System.DateTime data_sob { get; set; }
        public int id_type_dvij { get; set; }
        public int id_contag { get; set; }
        public int id_otd { get; set; }
        public int id_sotr { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
