//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OooPs14_dbEntities : DbContext
    {
        public OooPs14_dbEntities()
            : base("name=OooPs14_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adress_contragent> Adress_contragent { get; set; }
        public virtual DbSet<Arhiv_sotr> Arhiv_sotr { get; set; }
        public virtual DbSet<Banki> Bankis { get; set; }
        public virtual DbSet<Buchalterya> Buchalteryas { get; set; }
        public virtual DbSet<Chet_inBank> Chet_inBank { get; set; }
        public virtual DbSet<Con_Adress_Dom> Con_Adress_Dom { get; set; }
        public virtual DbSet<Con_adress_Point> Con_adress_Point { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Contragenti> Contragentis { get; set; }
        public virtual DbSet<Contragenti_contact> Contragenti_contact { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Dolzhnosti> Dolzhnostis { get; set; }
        public virtual DbSet<Dvijenie_Documenta> Dvijenie_Documenta { get; set; }
        public virtual DbSet<History_replace_sotr> History_replace_sotr { get; set; }
        public virtual DbSet<Mestnost> Mestnosts { get; set; }
        public virtual DbSet<Otdely> Otdelies { get; set; }
        public virtual DbSet<Prichina> Prichinas { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudnikis { get; set; }
        public virtual DbSet<Strana> Stranas { get; set; }
        public virtual DbSet<Tip_Documenta> Tip_Documenta { get; set; }
        public virtual DbSet<Ulica> Ulicas { get; set; }
        public virtual DbSet<Valyta> Valytas { get; set; }
        public virtual DbSet<Vid_Documenta> Vid_Documenta { get; set; }
    }
}
