//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulica()
        {
            this.Con_Adress_Dom = new HashSet<Con_Adress_Dom>();
        }
    
        public int id_ulica { get; set; }
        public string name_ulica { get; set; }
        public int id_mesto { get; set; }
        public string post_index_ulica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Con_Adress_Dom> Con_Adress_Dom { get; set; }
        public virtual Mestnost Mestnost { get; set; }
    }
}
